### ISSUE TITLE
A UTF-8 locale is required. Got ANSI_X3.4-1968

### ISSUE THREAD

**Issue by Mr-Nobody1** [mlabonne/llm-course#3]
Cannot log into hugging face after fine tuning the model.
![image](https://github.com/mlabonne/llm-course/assets/73386704/a4e6b861-62e9-4252-9275-d0ff71c2de1c)

**Comment by mlabonne** [comment]
This is a common issue with Google Colab, unfortunately. You can add the following code to prevent it:

```
import locale
locale.getpreferredencoding = lambda: "UTF-8"
```
