### ISSUE TITLE
Pls help, stuck with AutoGGUF

### ISSUE THREAD

**Issue by GameOverFlowChart** [mlabonne/llm-course#47]
I tried to make ggufs of different models (one that was already available and one which I made using the lazymergekit).

I always get the same error how ever. It's this one (I edited the model name out but it happens with both I tested. They are Mistral 7b based ones):
```
GML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla T4, compute capability 7.5, VMM: yes
main: build = 2151 (704359e2)
main: built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
main: quantizing 'ModelName/modelname.fp16.bin' to 'ModelName/modelname.Q4_K_S.gguf' as Q4_K_S
llama_model_quantize: failed to quantize: failed to open ModelName/modelname.fp16.bin: No such file or directory
main: failed to quantize model from 'ModelName/modelname.fp16.bin'
```

Also, before that error, I get another error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.25.2 which is incompatible.
torchaudio 2.1.0+cu121 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
torchdata 0.7.0 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
torchtext 0.16.0 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
torchvision 0.16.0+cu121 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
Successfully installed gguf-0.6.0 numpy-1.24.4 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.18.1 nvidia-nvjitlink-cu12-12.3.101 nvidia-nvtx-cu12-12.1.105 protobuf-4.25.2 torch-2.1.2

WARNING: The following packages were previously imported in this runtime:
  [numpy]
You must restart the runtime in order to use newly installed versions.
```

Is there any solution? I would like to try the model I merged locally, I was even able to evaluate it in the leaderboard but I can't turn it into GGUF.
Also is there a dedicated GitHub page for that notebook?

**Comment by kukedlc87** [comment]
If you notice, you're not replacing the variables in your model name and directory, it seems to me:

'ModelName/modelname.Q4_K_S.gguf'  <------- The real format is Username/ModelName
                                                                               Example: Kukedlc/Neuronal-7b

**Comment by GameOverFlowChart** [comment]
> If you notice, you're not replacing the variables in your model name and directory, it seems to me:
> 
> 'ModelName/modelname.Q4_K_S.gguf' <------- The real format is Username/ModelName Example: Kukedlc/Neuronal-7b

No as I wrote above I just edited the model name out because my models are just for test purposes and I don't want much attention for them.

I think the problem is that the code expects an older version of phyton but the colab has a new version but I'm not sure about that, just a guess.

**Comment by GameOverFlowChart** [comment]
> If you notice, you're not replacing the variables in your model name and directory, it seems to me:
> 
> 'ModelName/modelname.Q4_K_S.gguf' <------- The real format is Username/ModelName Example: Kukedlc/Neuronal-7b

But you are right that the username is not in the error for what ever reason. Instead the model name is twice with uppercase letters and without.

**Comment by GameOverFlowChart** [comment]
> If you notice, you're not replacing the variables in your model name and directory, it seems to me:
> 
> 'ModelName/modelname.Q4_K_S.gguf' <------- The real format is Username/ModelName Example: Kukedlc/Neuronal-7b

This is straight from the notebook:
`qtype = f"{MODEL_NAME}/{MODEL_NAME.lower()}.{method.upper()}.gguf"`

**Comment by kukedlc87** [comment]
I still insist that I believe the issue lies in the path, the directory you are passing. llama_model_quantize: failed to quantize: failed to open ModelName/modelname.fp16.bin: No such file or directory main: failed to quantize model from 'ModelName/modelname.fp16.bin'. If you look there, you should have a folder created where I saved the downloaded model; I also use it in Colab, and the code works fine for me.

**Comment by kukedlc87** [comment]
Share your code here if you want, and I'll review it.

**Comment by mlabonne** [comment]
Hey @GameOverFlowChart could you share a screenshot with all your input values? I did a lot of quants yesterday, I didn't run into this issue.

**Comment by GameOverFlowChart** [comment]
> Hey @GameOverFlowChart could you share a screenshot with all your input values? I did a lot of quants yesterday, I didn't run into this issue.

Here is an example which doesn't work. Also thanks for the tools you provide by the way.

![example](https://github.com/mlabonne/llm-course/assets/109205200/513d1093-5099-4b42-a789-c6f86f3d1eb2)

**Comment by GameOverFlowChart** [comment]
And here is the outcome
![example2](https://github.com/mlabonne/llm-course/assets/109205200/14c8c1fb-57e1-4993-a806-8979980b6a18)

**Comment by GameOverFlowChart** [comment]
> Try this: [MLABONNED QUANTIZATION CODE](https://colab.research.google.com/drive/1idKjze67gIEfQUUonYH5EVsAvTxiOqu2?authuser=1#scrollTo=vNPL9WYg78l-)

I will try, it seems like @mlabonne also tried to quantize it, but I'm not sure if he was successful (doesn't seem so).

**Comment by kukedlc87** [comment]
Now that I look closely, your model comes from some Llama model, right? I had the same problem. Lately, I've been using models derived from Mistral, but with Llama models, I encountered the same issue. I think the problem lies in being a Llama model; something happens when it creates the directory (in the same folder as the Llama models /models), and it can't load the model when quantizing it. Only @mlabonne  can help us with this, haha.

**Comment by kukedlc87** [comment]
The code I provided, run it and see if it performs quantization. It shouldn't fail because it's a model derived from Mistral.

**Comment by GameOverFlowChart** [comment]
> Now that I look closely, your model comes from some Llama model, right? I had the same problem. Lately, I've been using models derived from Mistral, but with Llama models, I encountered the same issue. I think the problem lies in being a Llama model; something happens when it creates the directory (in the same folder as the Llama models /models), and it can't load the model when quantizing it. Only @mlabonne can help us with this, haha.

No it's a merge between two Mistral based models.

**Comment by kukedlc87** [comment]
And did you try the new code?

**Comment by kukedlc87** [comment]
I'm getting the same error. It could be something in the config.json as well. I'll try to troubleshoot it in a bit.

**Comment by GameOverFlowChart** [comment]
> I'm getting the same error. It could be something in the config.json as well. I'll try to troubleshoot it in a bit.

Yes I also failed. It might help you maybe but I had the same problem as I tried to do the quantization with another model it's merged with:
argilla/distilabeled-OpenHermes-2.5-Mistral-7B

I thought I'm doing something wrong but maybe the colab can't quantize that model and models which are based on that.

**Comment by kukedlc87** [comment]
I think the issue lies in how you're doing the merge. In your repository, I found some oddities in config.json, and the tokenizer.model and generation_config.json files are missing. Compare it with one of my models or those from Labonne. I'd review the merge code.

**Comment by GameOverFlowChart** [comment]
> I think the issue lies in how you're doing the merge. In your repository, I found some oddities in config.json, and the tokenizer.model and generation_config.json files are missing. Compare it with one of my models or those from Labonne. I'd review the merge code.

Look at my comment above the same problem did happen with an unmerged model (maybe I should try that again to be sure).

The merge was made with the lazymergekit the code is here: https://colab.research.google.com/drive/1obulZ1ROXHjYLn6PPZJwRR6GzgQogxxb?usp=sharing

**Comment by kukedlc87** [comment]
I'm pretty sure it's what I mentioned last. I uploaded two of my files and it went past the previous error, but it's giving a discrepancy error now, obviously because it's from another model. Please check the config.json, it should have your model's name, not the merged one. 
<img width="585" alt="image" src="https://github.com/mlabonne/llm-course/assets/138949531/99405feb-98d6-4dfd-8d5e-cb4e3c4ba812">

**Comment by GameOverFlowChart** [comment]
> I'm pretty sure it's what I mentioned last. I uploaded two of my files and it went past the previous error, but it's giving a discrepancy error now, obviously because it's from another model. Please check the config.json, it should have your model's name, not the merged one. <img alt="image" width="585" src="https://private-user-images.githubusercontent.com/138949531/305515528-99405feb-98d6-4dfd-8d5e-cb4e3c4ba812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDc2MjQsIm5iZiI6MTcwODEwNzMyNCwicGF0aCI6Ii8xMzg5NDk1MzEvMzA1NTE1NTI4LTk5NDA1ZmViLTk4ZDYtNGRmZC04ZDVlLWNiNGUzYzRiYTgxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxODE1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjJlNTQyODA0Y2FmMWI5YTIxYTUzMDg2MDM5Zjc5Yzk5MWJkNDIwZmQ4MWI4Y2YyYjFmMmY1MTdjNzAxMTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G-3dxBiI9DEEQjiyrgU7YhVW97CaZMHd8TwPFNunOCc">

Did I get it right, at the model on hugging face, the config should contain it's own name in the "_name_or_path" attribute? I hope hugging face has an editor which let's me change that simply. But as I said the mergekit did that, it probably took the name of the model which I have chosen as the base model for the merge. I will try, it might take some time again. But I'm really surprised that the open llm leaderboard did not fail during the evaluation, I expected that to be much more complex than the gguf step.

**Comment by GameOverFlowChart** [comment]
Uhm wait but I have no idea where to get tokenizer.model and generation_config.json. Would I need to merge again? I see it now the other model which I merged does have a tokenizer.model file.

**Comment by GameOverFlowChart** [comment]
> I think the issue lies in how you're doing the merge. In your repository, I found some oddities in config.json, and the tokenizer.model and generation_config.json files are missing. Compare it with one of my models or those from Labonne. I'd review the merge code.

Uhm wait but I have no idea where to get tokenizer.model and generation_config.json. Would I need to merge again? I see it now the other model which I merged does have a tokenizer.model file. Uhm yeah it must be because both models use different models as the base. Look, the base model in question also doesn't have a tokenizer.model file which is probably the reason why the merge didn't generate one.

**Comment by GameOverFlowChart** [comment]
I try to gguf my second model first, if that works I think I know how I need to recreate the first one.

**Comment by GameOverFlowChart** [comment]
The other one worked
