### ISSUE TITLE
cuda out of memory 

### ISSUE THREAD

**Issue by Mr-Nobody1** [mlabonne/llm-course#5]
VRAM doesn't clear even when I run cell [7].
![image](https://github.com/mlabonne/llm-course/assets/73386704/cbbb59bc-ab3c-460e-8a8b-8f5141e4050c)

**Comment by mlabonne** [comment]
Hmm weird usually it works. In this case, I recommend restarting the notebook, executing the first three cells (so you have the required parameters), and then running the model for inference.
