### ISSUE TITLE
Error when using HuggingChat Assistant

### ISSUE THREAD

**Issue by samuelcai-chancetop** [mlabonne/llm-course#69]
See the screen shot
<img width="1320" alt="Screenshot 2024-05-10 at 18 06 37" src="https://github.com/mlabonne/llm-course/assets/59716697/da3fae89-41d2-425f-8e72-5daa8060f539">

**Comment by mlabonne** [comment]
Thanks it's been reported to Hugging Face they're working on it https://github.com/huggingface/chat-ui/pull/1129

**Comment by mishig25** [comment]
The issue is fixed now 😃

**Comment by samuelcai-chancetop** [comment]
Confirm it is fixed :)
