### ISSUE TITLE
any reason why the finetuning llama notebook is running only on colab?

### ISSUE THREAD

**Issue by yairVanti** [mlabonne/llm-course#7]
i tried running the same notebook on gcp A100 machine, and it failed on :

`File ~/.local/lib/python3.9/site-packages/transformers/utils/bitsandbytes.py:109, in set_module_quantized_tensor_to_device(module, tensor_name, device, value, fp16_statistics)
    107     new_value = old_value.to(device)
    108 elif isinstance(value, torch.Tensor):
--> 109     new_value = value.to(device)
    110 else:
    111     new_value = torch.tensor(value, device=device)

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

on colab it work perfectly.
any idea ?

**Comment by mlabonne** [comment]
It could be something related to the CUDA version this machine is using. I'd also recommend updating the libraries (especially transformers, accelerate, and bitsandbytes), it might solve a compatibility issue.
