### ISSUE TITLE
Article link is wrong?

### ISSUE THREAD

**Issue by samuelcai-chancetop** [mlabonne/llm-course#70]
See screen shot
<img width="967" alt="Screenshot 2024-05-13 at 16 54 33" src="https://github.com/mlabonne/llm-course/assets/59716697/752260a6-0462-432b-8cce-14b1808e84c9">
Article of "Fine-tune Mistral-7b with SFT" is the same as "Fine-tune Llama 2 with SFT".
Maybe we should remove the row? I cannot find the article about "Fine-tune Mistral-7b with SFT" in the blog website.

**Comment by mlabonne** [comment]
Yes it's not super clear but the idea is that you can replace Llama 2 7B with Mistral-7B in this case and it would be the same article. I didn't write one specific to Mistral-7B because there's basically zero change

**Comment by samuelcai-chancetop** [comment]
oh, I see, will close this.
