### ISSUE TITLE
"LLM Training: RLHF and Its Alternatives" article URL is not correct

### ISSUE THREAD

**Issue by MosaabMuhammed** [mlabonne/llm-course#71]
in the *5. Reinforcement Learning from Human Feedback*, the URL for *[LLM Training: RLHF and Its Alternatives](https://substack.com/profile/27393275-sebastian-raschka-phd)* is not correct.

here's is the correct URL: https://magazine.sebastianraschka.com/p/llm-training-rlhf-and-its-alternatives

![image](https://github.com/mlabonne/llm-course/assets/35741087/fd373724-9f7b-4ab9-aada-59a621b32e80)

**Comment by mlabonne** [comment]
Thanks, this is fixed!
