### ISSUE TITLE
Fine-tune Llama 3 with ORPO HuggigFace Hub Push Issue

### ISSUE THREAD

**Issue by claytoncohn** [mlabonne/llm-course#84]
Greetings! In your Fine-tune Llama 3 with ORPO tutorial, I am receiving an error when I try to push to the Hub:

```
...

trainer.train()
trainer.save_model(new_model)

del trainer, model
gc.collect()
torch.cuda.empty_cache()

tokenizer = AutoTokenizer.from_pretrained(base_model)
fp16_model = AutoModelForCausalLM.from_pretrained(
    base_model,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map="auto",
)
fp16_model, tokenizer = setup_chat_format(fp16_model, tokenizer)

model = PeftModel.from_pretrained(fp16_model, new_model)
model = model.merge_and_unload()

model.push_to_hub(new_model, use_temp_dir=False)
tokenizer.push_to_hub(new_model, use_temp_dir=False)
```

```
---------------------------------------------------------------------------

IsADirectoryError                         Traceback (most recent call last)

[<ipython-input-29-aa0cf4290d65>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model.push_to_hub(new_model, use_temp_dir=False)
      2 tokenizer.push_to_hub(new_model, use_temp_dir=False)

4 frames

[/usr/lib/python3.10/pathlib.py](https://localhost:8080/#) in open(self, mode, buffering, encoding, errors, newline)
   1117         if "b" not in mode:
   1118             encoding = io.text_encoding(encoding)
-> 1119         return self._accessor.open(self, mode, buffering, encoding, errors,
   1120                                    newline)
   1121 

IsADirectoryError: [Errno 21] Is a directory: 'claytoncohn/TEST_ORPO_LLaMA3'
```

When I make call ```push_to_hub```, a model repo is created on my HF account and a .gitattributes file is created for the initial commit, but then the error is thrown. 

There is a similar issue addressed on huggingface (https://github.com/huggingface/transformers/issues/28543), but I can't seem to figure out what I am doing wrong. 

**EDIT:** Pursuant to the above huggingface GitHub issue, I tried removing the local Colab directory ```claytoncohn/TEST_ORPO_LLaMA3``` to avoid the conflict; however, I then received a file not found error. It seems that even though the base model is merged with the adapters in the Colab environment, the call to ```model.push_to_hub``` attempts to retrieve the model locally (i.e., from the folder w/ the saved trained adapters) from the same path as the repo that I am trying to push to on HuggingFace Hub.

Thanks!

**Comment by mlabonne** [comment]
Hey, indeed your error is due to the fact you currently have a directory `claytoncohn/TEST_ORPO_LLaMA3`. Regarding the second error, I'd need the traceback to help you.

**Comment by claytoncohn** [comment]
Sure! The folder creating the conflict, ```claytoncohn/TEST_ORPO_LLaMA3```, initially contained the trained adapters (as a result of the call to ```trainer.save_model(new_model)```). However, when I removed the items in this folder and replaced them with the merged model, I still have the same issue due to the conflict. 

If I remove the local directory to resolve the conflict, I receive an error that the the directory can't be found:

```
...

new_model = "claytoncohn/TEST_ORPO_LLaMA3"

...

delete_folder(pathlib.Path(new_model.split("/")[0]))
!ls 

#Confirmed that the claytoncohn/TEST_ORPO_LLaMA3 directory is gone
results  sample_data  wandb 
```

```
model.push_to_hub(new_model, use_temp_dir=False)
tokenizer.push_to_hub(new_model, use_temp_dir=False)

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-24-aa0cf4290d65>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model.push_to_hub(new_model, use_temp_dir=False)
      2 tokenizer.push_to_hub(new_model, use_temp_dir=False)

2 frames

[/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py](https://localhost:8080/#) in push_to_hub(self, *args, **kwargs)
   2661         if tags:
   2662             kwargs["tags"] = tags
-> 2663         return super().push_to_hub(*args, **kwargs)
   2664 
   2665     def get_memory_footprint(self, return_buffers=True):

[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in push_to_hub(self, repo_id, use_temp_dir, commit_message, private, token, max_shard_size, create_pr, safe_serialization, revision, commit_description, tags, **deprecated_kwargs)
    886 
    887         with working_or_temp_dir(working_dir=working_dir, use_temp_dir=use_temp_dir) as work_dir:
--> 888             files_timestamps = self._get_files_timestamps(work_dir)
    889 
    890             # Save all files.

[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in _get_files_timestamps(self, working_dir)
    696         Returns the list of files with their last modification timestamp.
    697         """
--> 698         return {f: os.path.getmtime(os.path.join(working_dir, f)) for f in os.listdir(working_dir)}
    699 
    700     def _upload_modified_files(

FileNotFoundError: [Errno 2] No such file or directory: 'TEST_ORPO_LLaMA3'
```

**Comment by mlabonne** [comment]
Sorry for the late reply. I think you need a temp folder to store the files that are uploaded to the HF Hub. It doesn't look necessary indeed, but I don't think I can change it in the code since it relies on HF's implementation.

**Comment by claytoncohn** [comment]
No worries, I appreciate the response! I'll continue using temp folder going forward and will close the issue. Thanks again!

**Comment by claytoncohn** [comment]
No worries, I appreciate the response! I'll continue using temp folder going forward and will close the issue. Thanks again!
