### ISSUE TITLE
All fine-tuned models should be  available for inference  with HF TGI

### ISSUE THREAD

**Issue by elliotthwang** [mlabonne/llm-course#9]
model = PeftModel.from_pretrained(base_model, new_model)
model = model.merge_and_unload()

All fine-tuned models should be  available for inference  with HF TGI
However showed NotSupportedError:   Model ` fine-tuned mode` is not available for inference with this client. 
Is there any way to cope with?

**Comment by mlabonne** [comment]
Sorry I haven't tried to use TGI with this fine-tuned model.

**Comment by mlabonne** [comment]
Here's an article that should address this question: https://mlabonne.github.io/blog/posts/Quantize_Llama_2_models_using_ggml.html

**Comment by elliotthwang** [comment]
Thanks a lot!
Yes, indeed  your Quantize Llama 2 models using ggml.ipynb already be sufficient to convert HF models into GGUF format.
